### ISSUE TITLE
Compiler warnings "unknown escape characters" on Windows

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/arduino-preprocessor#5]
Seems like https://github.com/arduino/arduino-preprocessor/commit/8217efdb2abbf75d36fd9e3f410a9d06c0001d14 did not fully address all the Windows pathnames.

I tested today with "arduino-PR-beta1.9-BUILD-26".

To reproduce problem, set Compiler Warnings to "All" in File > Preferences.  Then compile this sketch for Arduino Zero.

    void setup() {
      Serial.begin(9600);
    }
    
    void loop() {
      dosomething();
      delay(1000);
    }
    
    void dosomething() {
      Serial.println("Hello world");
    }

The compiler warnings scroll by quickly.  You may need to scroll back up to see them.  Here's a screenshot:

![capture](https://user-images.githubusercontent.com/965463/33805320-bacbfea2-dd6b-11e7-8126-157176b7eb44.PNG)

**Comment by PaulStoffregen** [comment]
Here's the last several lines from dosomething.ino.cpp in the temp build folder.

Some have all the Windows backslash characters properly escaped, but others have only the first one escaped.  :-(


    extern uint32_t UHD_Pipe_Read(uint32_t ul_pipe, uint32_t ul_size, uint8_t* data);
    extern void UHD_Pipe_Write(uint32_t ul_pipe, uint32_t ul_size, uint8_t* data);
    extern void UHD_Pipe_Send(uint32_t ul_pipe, uint32_t ul_token_type);
    extern uint32_t UHD_Pipe_Is_Transfer_Complete(uint32_t ul_pipe, uint32_t ul_token_type);


    }
    # 132 "C:\\Users\\me\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.6.15\\cores\\arduino/Arduino.h" 2
    # 2 "C:\\Users\\me\\AppData\\Local\\Temp\\arduino_build_552271\\sketch\\dosomething.ino.cpp" 2
    # 1 "C:\\Users\\me\\Documents\\Arduino\\dosomething\\dosomething.ino"
    # 1 "C:\\Users\\me\\Documents\\Arduino\\dosomething\\dosomething.ino"
    void setup() {
      Serial.begin(9600);
    }

    #line 5 "C:\\Users\me\Documents\Arduino\dosomething\dosomething.ino"
    extern "C" void loop();
    #line 10 "C:\\Users\me\Documents\Arduino\dosomething\dosomething.ino"
    void dosomething();
    #line 5 "C:\\Users\me\Documents\Arduino\dosomething\dosomething.ino"
    void loop() {
      dosomething();
      delay(1000);
    }

    void dosomething() {
      Serial.println("hello world");
    }

**Comment by matthijskooijman** [comment]
@facchinm, why does that commit also change a bunch of cygwin dlls? Doesn't seem related to the subject of the commit?
